import {NextRequest,NextResponse} from "next/server";
import {adminClient,userClient} from "../../../../lib/supabase-server";
export const runtime="nodejs";
async function authorized(req:NextRequest){const token=req.headers.get("authorization")?.replace(/^Bearer\s+/,"");if(!token)return false;const {data:{user}}=await userClient(token).auth.getUser(token);if(!user)return false;const {data:p}=await adminClient().from("profiles").select("role").eq("id",user.id).single();return p?.role==="admin";}
export async function POST(req:NextRequest){try{if(!await authorized(req))return NextResponse.json({error:"Admin required"},{status:403});const b=await req.json();const start=new Date(b.startsAt),end=new Date(b.endsAt),capacity=Number(b.capacity);
if(!b.title||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start<=new Date()||end<=start||!Number.isInteger(capacity)||capacity<1||capacity>8)return NextResponse.json({error:"Check class dates and choose up to 8 places"},{status:400});
const token=req.headers.get("authorization")!.replace(/^Bearer\s+/,"");const {data:id,error}=await userClient(token).rpc("admin_publish_gym_bootcamp",{p_title:String(b.title),p_description:String(b.description||""),p_starts_at:start.toISOString(),p_ends_at:end.toISOString(),p_capacity:capacity});
if(error)return NextResponse.json({error:error.message},{status:409});return NextResponse.json({id});}catch(e){console.error(e);return NextResponse.json({error:"Could not create bootcamp"},{status:500})}}
export async function PATCH(req:NextRequest){try{if(!await authorized(req))return NextResponse.json({error:"Admin required"},{status:403});const b=await req.json();const db=adminClient();const [{data:bookings},{data:holds}]=await Promise.all([db.from("bootcamp_bookings").select("id").eq("class_id",b.id).eq("status","confirmed").limit(1),db.from("bootcamp_bookings").select("id").eq("class_id",b.id).eq("status","pending").gt("hold_expires_at",new Date().toISOString()).limit(1)]);if(bookings?.length||holds?.length)return NextResponse.json({error:"This class has bookings. Contact customers before changing or cancelling it."},{status:409});const token=req.headers.get("authorization")!.replace(/^Bearer\s+/,"");const {error}=await userClient(token).rpc("admin_cancel_gym_bootcamp",{p_class_id:b.id});if(error)return NextResponse.json({error:error.message},{status:409});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:"Could not cancel class"},{status:500})}}
