"use client";import{useEffect,useState}from"react";import{supabase}from"../../lib/supabase";
export default function Admin(){const[start,setStart]=useState(""),[kind,setKind]=useState("pt"),[note,setNote]=useState("Personal training"),[msg,setMsg]=useState(""),[bookings,setBookings]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[settings,setSettings]=useState<any>(null),[reviews,setReviews]=useState<any[]>([]),[weeks,setWeeks]=useState(1),[customer,setCustomer]=useState(""),[customerEmail,setCustomerEmail]=useState(""),[party,setParty]=useState(1);
async function load(){const sb=supabase();const from=new Date(),to=new Date(Date.now()+30*864e5);const[{data:b,error},{data:m},{data:s},{data:r}]=await Promise.all([sb.rpc("admin_dashboard",{p_from:from.toISOString(),p_to:to.toISOString()}),sb.rpc("admin_members"),sb.from("gym_settings").select("*").single(),sb.rpc("admin_health_reviews")]);if(error){setMsg(error.message);return}setBookings(b||[]);setMembers(m||[]);setSettings(s);setReviews(r||[])}
useEffect(()=>{load()},[]);
async function block(){const rpc=weeks>1?"admin_block_recurring":"admin_block_slot";const args=weeks>1?{p_starts_at:new Date(start).toISOString(),p_kind:kind,p_note:note,p_weeks:weeks}:{p_starts_at:new Date(start).toISOString(),p_kind:kind,p_note:note};const{data,error}=await supabase().rpc(rpc,args);setMsg(error?.message||(weeks>1?`${data} slots blocked.`:"Slot blocked."));if(!error){setStart("");load()}}
async function reserve(){const{error}=await supabase().rpc("admin_create_reservation",{p_starts_at:new Date(start).toISOString(),p_name:customer,p_email:customerEmail||null,p_party_size:party,p_note:note});setMsg(error?.message||"Customer reservation added.");if(!error){setStart("");setCustomer("");setCustomerEmail("");load()}}
async function cancel(id:string){if(!confirm("Cancel this booking/block? Member credits will be returned and paid customer bookings will be refunded where applicable."))return;const sb=supabase(),{data:{session}}=await sb.auth.getSession();if(!session){location.href="/login";return}const r=await fetch("/api/admin/bookings/cancel",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({id})});const j=await r.json();setMsg(j.message||j.error||"Cancelled.");load()}
async function clearReview(x:any){if(!confirm("Confirm this person is cleared to train after reviewing their health information?"))return;const{error}=await supabase().rpc("admin_clear_health_review",{p_kind:x.kind,p_review_id:x.review_id});setMsg(error?.message||"Health review cleared.");load()}
async function adjust(x:any){const n=prompt("Set bookings remaining",String(x.bookings_remaining));if(n===null)return;const{error}=await supabase().rpc("admin_adjust_entitlement",{p_membership_id:x.membership_id,p_bookings:Number(n),p_guest_passes:null});setMsg(error?.message||"Allowance updated.");load()}
async function saveSettings(){const s=settings;const{error}=await supabase().rpc("admin_update_settings",{p_open:s.open_time,p_close:s.close_time,p_session:Number(s.session_minutes),p_turnover:Number(s.turnover_minutes),p_cancel:Number(s.cancellation_hours),p_max:Number(s.max_people),p_payg:Number(s.payg_price_pence),p_opening_date:s.opening_date,p_member_advance:Number(s.member_advance_booking_days),p_payg_advance:Number(s.payg_advance_booking_days)});setMsg(error?.message||"Gym settings updated.");load()}
return <main><section><p className="eyebrow">OWNER CONTROL</p><h2>Hall Farm Gym admin</h2>{msg&&<p>{msg}</p>}<div className="notice"><h3>Block the gym</h3><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="pt">Personal training</option><option value="maintenance">Maintenance</option><option value="admin_block">Closure / other</option></select><input value={note} onChange={e=>setNote(e.target.value)}/><label>Repeat weekly<select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{[1,2,4,6,8,12,26,52].map(n=><option key={n} value={n}>{n===1?"No":`${n} weeks`}</option>)}</select></label><button className="primary" onClick={block} disabled={!start}>Block slot</button></div><div className="notice"><h3>Add customer reservation</h3><p>Use this for a booking you create manually for a customer.</p><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/><input placeholder="Customer name" value={customer} onChange={e=>setCustomer(e.target.value)}/><input type="email" placeholder="Email (optional)" value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)}/><select value={party} onChange={e=>setParty(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button className="primary" onClick={reserve} disabled={!start||!customer.trim()}>Add reservation</button></div>
<h2>Next 30 days</h2><div className="cards">{bookings.map(x=><article key={x.id}><h3>{new Date(x.starts_at).toLocaleString("en-GB")}</h3><p><strong>{x.kind}</strong>{x.plan_name?` · ${x.plan_name}`:""}<br/>{x.customer_name||x.customer_email||x.admin_note||"Admin block"}<br/>{x.party_size} people{x.guest_name?` · Guest: ${x.guest_name}`:""}</p>{x.status==="confirmed"&&<button className="secondary" onClick={()=>cancel(x.id)}>Cancel / release</button>}</article>)}</div>
<h2>Health reviews</h2>{reviews.length?<div className="cards">{reviews.map((x:any,i:number)=><article key={i}><h3>{x.person_name||x.email}</h3><p>{x.kind} · {x.email}<br/>Flagged health questionnaire — review before training.</p><button className="primary" onClick={()=>clearReview(x)}>Clear for training</button></article>)}</div>:<p>No health questionnaires currently flagged for review.</p>}<h2>Memberships</h2><div className="cards">{members.map(x=><article key={x.membership_id}><h3>{x.owner_name||x.owner_email}</h3><p>{x.plan_name} · {x.status}<br/>{x.bookings_remaining} bookings remaining</p><button onClick={()=>adjust(x)}>Adjust allowance</button></article>)}</div>
{settings&&<><h2>Gym settings</h2><div className="formgrid">{[["open_time","Opening time"],["close_time","Closing time"],["session_minutes","Session minutes"],["turnover_minutes","Turnover minutes"],["cancellation_hours","Cancellation hours"],["max_people","Max people"],["payg_price_pence","PAYG price (pence)"],["opening_date","Opening date"],["member_advance_booking_days","Member booking window (days)"],["payg_advance_booking_days","PAYG booking window (days)"]].map(([k,l])=><label key={k}>{l}<input value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={saveSettings}>Save settings</button></>}</section></main>}