"use client";import{useEffect,useState}from"react";import{supabase}from"../../lib/supabase";
export default function Admin(){const[start,setStart]=useState(""),[kind,setKind]=useState("pt"),[note,setNote]=useState("Personal training"),[msg,setMsg]=useState(""),[bookings,setBookings]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[settings,setSettings]=useState<any>(null),[reviews,setReviews]=useState<any[]>([]);
async function load(){const sb=supabase();const from=new Date(),to=new Date(Date.now()+30*864e5);const[{data:b,error},{data:m},{data:s},{data:r}]=await Promise.all([sb.rpc("admin_dashboard",{p_from:from.toISOString(),p_to:to.toISOString()}),sb.rpc("admin_members"),sb.from("gym_settings").select("*").single(),sb.rpc("admin_health_reviews")]);if(error){setMsg(error.message);return}setBookings(b||[]);setMembers(m||[]);setSettings(s);setReviews(r||[])}
useEffect(()=>{load()},[]);
async function block(){const{error}=await supabase().rpc("admin_block_slot",{p_starts_at:new Date(start).toISOString(),p_kind:kind,p_note:note});setMsg(error?.message||"Slot blocked.");if(!error){setStart("");load()}}
async function cancel(id:string){if(!confirm("Cancel this booking/block? Member credits will be returned where applicable."))return;const{error}=await supabase().rpc("admin_cancel_booking",{p_booking_id:id});setMsg(error?.message||"Cancelled.");load()}
async function adjust(x:any){const n=prompt("Set bookings remaining",String(x.bookings_remaining));if(n===null)return;const g=prompt("Set guest passes remaining",String(x.guest_passes_remaining));if(g===null)return;const{error}=await supabase().rpc("admin_adjust_entitlement",{p_membership_id:x.membership_id,p_bookings:Number(n),p_guest_passes:Number(g)});setMsg(error?.message||"Allowance updated.");load()}
async function saveSettings(){const s=settings;const{error}=await supabase().rpc("admin_update_settings",{p_open:s.open_time,p_close:s.close_time,p_session:Number(s.session_minutes),p_turnover:Number(s.turnover_minutes),p_cancel:Number(s.cancellation_hours),p_max:Number(s.max_people),p_payg:Number(s.payg_price_pence),p_opening_date:s.opening_date,p_member_advance:Number(s.member_advance_booking_days),p_payg_advance:Number(s.payg_advance_booking_days)});setMsg(error?.message||"Gym settings updated.");load()}
return <main><section><p className="eyebrow">OWNER CONTROL</p><h2>Hall Farm Gym admin</h2>{msg&&<p>{msg}</p>}<div className="notice"><h3>Block the gym</h3><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="pt">Personal training</option><option value="maintenance">Maintenance</option><option value="admin_block">Closure / other</option></select><input value={note} onChange={e=>setNote(e.target.value)}/><button className="primary" onClick={block} disabled={!start}>Block slot</button></div>
<h2>Next 30 days</h2><div className="cards">{bookings.map(x=><article key={x.id}><h3>{new Date(x.starts_at).toLocaleString("en-GB")}</h3><p><strong>{x.kind}</strong>{x.plan_name?` · ${x.plan_name}`:""}<br/>{x.customer_name||x.customer_email||x.admin_note||"Admin block"}<br/>{x.party_size} people{x.guest_name?` · Guest: ${x.guest_name}`:""}</p>{x.status==="confirmed"&&<button className="secondary" onClick={()=>cancel(x.id)}>Cancel / release</button>}</article>)}</div>
<h2>Health reviews</h2>{reviews.length?<div className="cards">{reviews.map((x:any,i:number)=><article key={i}><h3>{x.person_name||x.email}</h3><p>{x.kind} · {x.email}<br/>Flagged health questionnaire — review before training.</p></article>)}</div>:<p>No health questionnaires currently flagged for review.</p>}<h2>Memberships</h2><div className="cards">{members.map(x=><article key={x.membership_id}><h3>{x.owner_name||x.owner_email}</h3><p>{x.plan_name} · {x.status}<br/>{x.bookings_remaining} bookings · {x.guest_passes_remaining} guest passes</p><button onClick={()=>adjust(x)}>Adjust allowance</button></article>)}</div>
{settings&&<><h2>Gym settings</h2><div className="formgrid">{[["open_time","Opening time"],["close_time","Closing time"],["session_minutes","Session minutes"],["turnover_minutes","Turnover minutes"],["cancellation_hours","Cancellation hours"],["max_people","Max people"],["payg_price_pence","PAYG price (pence)"],["opening_date","Opening date"],["member_advance_booking_days","Member booking window (days)"],["payg_advance_booking_days","PAYG booking window (days)"]].map(([k,l])=><label key={k}>{l}<input value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={saveSettings}>Save settings</button></>}</section></main>}