"use client";
import{useEffect,useState}from"react";import{supabase}from"../../lib/supabase";
export default function Join(){const[plan,setPlan]=useState("solo"),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{setPlan((new URLSearchParams(location.search).get("plan")||"solo").toLowerCase());const sb=supabase();sb.auth.getUser().then(async({data:{user}})=>{if(user){setEmail(user.email||"");const{data:p}=await sb.from("profiles").select("phone").eq("id",user.id).maybeSingle();if(p?.phone)setPhone(p.phone)}})},[]);
async function start(){setBusy(true);setMsg("");const sb=supabase();const{data:{user}}=await sb.auth.getUser();
if(!user){if(!phone||!email||password.length<8){setMsg("Enter your mobile number, email and a password of at least 8 characters.");setBusy(false);return}
 const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,email,password})});const j=await r.json();if(!r.ok){setMsg(j.error||"Could not create your account.");setBusy(false);return}
 const{error}=await sb.auth.signInWithPassword({phone:phone.replace(/\s+/g,""),password});if(error){setMsg("Your account was created, but sign-in failed. Use Member login.");setBusy(false);return}
 localStorage.setItem("hallFarmMobile",phone);
}
const{data:on}=await sb.rpc("onboarding_status");const status=on?.[0];if(!(status?.profile_complete&&status?.health_complete&&status?.legal_complete&&!status?.needs_review)){location.href=`/onboarding?next=join&plan=${plan}`;return}const{data:{session}}=await sb.auth.getSession();const r=await fetch("/api/stripe/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({type:"membership",plan})});const j=await r.json();if(j.url)location.href=j.url;else{setMsg(j.error||"Could not start checkout.");setBusy(false)}}
return <main><section className="hero"><p className="eyebrow">JOIN THE HALL FARM GYM</p><h2>{plan.toUpperCase()} membership</h2><p>10 private gym sessions each month. Duo and Trio memberships share the same 10 sessions between the named members. One person sets up and pays for the membership, then adds the other named member or members from their account. You can add one extra non-member to a session for £5.</p><p className="formhint">Your mobile number is your main membership contact. Your email is kept for receipts and account records.</p><form className="joinform" onSubmit={e=>{e.preventDefault();start()}}><div className="joinfields"><input type="tel" inputMode="tel" autoComplete="tel" placeholder="Mobile number" value={phone} onChange={e=>setPhone(e.target.value)}/>{!email&&<input type="email" inputMode="email" autoComplete="email" autoCapitalize="none" autoCorrect="off" spellCheck={false} placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/>} {!email||!phone?<input type="password" autoComplete="new-password" placeholder="Create a password" value={password} onChange={e=>setPassword(e.target.value)}/>:null}</div><button type="submit" className="primary" disabled={busy}>{busy?"Please wait…":"Continue"}</button></form>{msg&&<p>{msg}</p>}<p><a href="/login">Already have an account? Member login</a></p></section></main>}