export const metadata={title:"Privacy policy"};
export default function Privacy(){return <main><section className="policy"><p className="eyebrow">YOUR INFORMATION</p><h2>Privacy policy</h2><p>Last updated: 3 October 2026. The Hall Farm Gym is operated through WrayFitness. For privacy requests or complaints, email <a href="mailto:wrayfitness04@gmail.com">wrayfitness04@gmail.com</a>.</p>
<h3>Information we use</h3><p>We may use your name, email, phone number, emergency-contact details, account details, membership and booking history, attendance and cancellation records, payment references, communications with us, legal/safety acknowledgements and health questionnaire answers. We do not ask you to send us full payment-card details.</p>
<h3>Why we use it and our lawful bases</h3><p>We use ordinary personal data where necessary to provide and administer the service and our contract with you, to meet legal obligations, and for legitimate interests such as protecting the facility, preventing misuse, keeping appropriate business records and handling disputes. Where we rely on legitimate interests, we consider the impact on your rights. Health questionnaire information is health data and receives additional protection. We rely on your explicit consent for the health-data processing used to assess gym safety and eligibility. You may withdraw that consent by contacting us; withdrawal does not affect processing already carried out, but we may be unable to permit training if we cannot establish the required safety information.</p>
<h3>Who processes information</h3><p>Stripe provides payment processing; Supabase provides account, database and authentication services; Vercel hosts and delivers the website/app; and Resend provides transactional email delivery. We disclose information only where reasonably necessary for those services, to professional advisers/insurers where appropriate, or where required or permitted by law. If a service provider processes information outside the UK, we use the provider subject to the applicable UK data-transfer rules and safeguards.</p>
<h3>Health information</h3><p>Health answers are special-category personal data. We collect only the limited questionnaire information needed for the gym-safety process, restrict access, and record the consent and document version accepted. Do not send additional medical records by ordinary email unless we specifically ask you to use an appropriate method.</p>
<h3>CCTV</h3><p>Safety or security CCTV may operate at the gym. Where cameras are in operation, signs will be displayed before or within the monitored area. CCTV is used for legitimate interests in safety, security, incident investigation and protection of people and property. Access should be limited to authorised people and footage is kept only for the shortest period reasonably necessary for those purposes, unless a particular incident, legal claim or lawful request requires it to be preserved for longer. We do not use facial recognition.</p>
<h3>Retention</h3><p>We keep account and booking information while it is needed to provide the service. Transaction, contract and accounting records may be retained for up to six years where needed for tax, accounting, contractual or legal-record purposes. Health information is reviewed and kept only while reasonably needed for safety and any applicable legal-claim requirements, then deleted or anonymised. Security records and CCTV are not kept simply because storage space is available. Where a specific dispute, safeguarding issue or legal obligation applies, relevant information may be retained for longer.</p>
<h3>Your rights</h3><p>Depending on the circumstances, you may have rights of access, rectification, erasure, restriction, data portability and objection, and the right to withdraw consent. We normally have one month to respond to a valid data-rights request. You can complain to us first and you also have the right to complain to the UK's <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner's Office</a>.</p>
<h3>Cookies and local storage</h3><p>The website/app uses storage that is necessary for functions such as authentication, security and the installable app experience. We do not currently use advertising or behavioural-tracking cookies. If non-essential analytics or marketing cookies are introduced, we will update this notice and obtain consent where required before setting them.</p>
<h3>Security</h3><p>We use HTTPS, access controls, restricted owner/admin permissions, database row-level security where appropriate, payment processing through Stripe, and security headers on the website. No internet service can guarantee absolute security. Please use a unique password and do not share private booking links or gym access codes.</p>
<h3>Changes and contact</h3><p>We may update this notice as the service changes. Material changes affecting how we use personal information will be brought to users' attention where appropriate. For questions, rights requests or complaints, email <a href="mailto:wrayfitness04@gmail.com">wrayfitness04@gmail.com</a>.</p></section></main>}
