"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type P={code:string;name:string;price_pence:number;monthly_bookings:number;named_members:number;guest_passes:number};
export default function Home(){const[p,setP]=useState<P[]>([]);
useEffect(()=>{supabase().from("membership_plans").select("code,name,price_pence,monthly_bookings,named_members,guest_passes").eq("active",true).order("price_pence").then(({data})=>setP(data||[]))},[]);
return <main><header><a className="brand" href="/" aria-label="The Hall Farm Gym home"><img src="/hall-farm-gym-logo.webp" alt="The Hall Farm Gym"/></a><nav><a href="#membership">Membership</a><a href="/book">Book</a><a href="/login">Member login</a></nav></header>
<section className="hero"><p className="eyebrow">PRIVATE HIRE • HALL FARM</p><h1>YOUR GYM.<br/>YOUR TIME.</h1><p className="lead">A private gym session with the whole space to yourself. Train on your own, with a friend or with your own small group — no crowds and no waiting around for equipment.</p><div className="actions"><a className="primary" href="/book">Book a session</a><a className="secondary" href="/join?plan=solo">Become a member</a></div><div className="facts"><span>07:00–21:00</span><span>50 minute private sessions</span><span>Up to 5 people</span></div></section>
<section id="membership"><p className="eyebrow">MEMBERSHIP</p><h2>Simple memberships. Private sessions.</h2><div className="cards">{p.map(x=><article key={x.code}><h3>{x.name}</h3><div className="price">£{x.price_pence/100}<small>/month</small></div><p>{x.monthly_bookings} private gym bookings each month.</p><p>{x.named_members>1?`Shared by ${x.named_members} named members — the allowance remains ${x.monthly_bookings} whole-gym bookings.`:"For one named member."}</p>{x.guest_passes>0&&<p>{x.guest_passes} free Bring-a-Friend pass each month.</p>}<a className="primary" href={`/join?plan=${x.code}`}>Choose {x.name}</a></article>)}</div></section>
<section id="wray-fitness" className="wrayfitness"><img className="wf-brand" src="/wray-fitness-logo.webp" alt="WrayFitness"/><div><p className="eyebrow">PERSONAL TRAINING & CLASSES</p><h2>WrayFitness</h2><p>Personal training, strength & conditioning and small-group classes at Hall Farm, run through WrayFitness by Peter Wray — Level 6 (Hons) Strength & Conditioning graduate and Level 3 Personal Trainer.</p><p>Want to know more about PT or classes?</p><div className="actions"><a className="primary" href="mailto:wrayfitness04@gmail.com">Email WrayFitness</a><a className="secondary" href="https://wa.me/447376246998?text=Hi%2C%20I%27m%20interested%20in%20personal%20training.%20Please%20could%20I%20get%20some%20more%20info%3F" target="_blank" rel="noopener noreferrer">WhatsApp PT enquiry</a></div><p className="contactnote">wrayfitness04@gmail.com · 07376 246998</p></div></section><section className="book"><p className="eyebrow">PRIVATE SESSION</p><h2>Want to train without a busy gym?</h2><p>Book the whole gym for £12.50 PAYG, or use one of your monthly member sessions.</p><a className="primary" href="/book">See available sessions</a></section><footer>THE HALL FARM GYM • HALL FARM</footer></main>}