"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
type Class={id:string;title:string;description:string;starts_at:string;ends_at:string;capacity:number;remaining:number;price_pence:number};
type Person={user_id:string|null;full_name:string|null;email:string;is_cleared:boolean;is_owner:boolean};
export default function Bootcamps(){
 const[classes,setClasses]=useState<Class[]>([]),[loading,setLoading]=useState(true),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState<string[]>([]),[member,setMember]=useState(false),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function load(){try{const r=await fetch("/api/bootcamps",{cache:"no-store"}),j=await r.json();setClasses(j.classes||[])}catch(e){setMsg("Unable to load the timetable.")}setLoading(false)}
 useEffect(()=>{load();async function auth(){const sb=supabase(),{data:{user}}=await sb.auth.getUser();if(!user)return;const{data:e}=await sb.rpc("my_booking_entitlement");if(!e?.[0]?.has_active_membership)return;setMember(true);const{data:p}=await sb.rpc("my_membership_members");const allowed=(p||[]).filter((x:Person)=>x.is_cleared&&x.user_id);setPeople(allowed);setSelected(allowed.filter((x:Person)=>x.user_id===user.id).map((x:Person)=>x.user_id!))}auth()},[]);
 async function useCredit(c:Class){if(selected.length>c.remaining){setMsg("Not enough places remain for your group.");return}setBusy(c.id);setMsg("");const sb=supabase(),{data:{session}}=await sb.auth.getSession();if(!session){location.href="/login";return}try{const r=await fetch("/api/bootcamps/member",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({classId:c.id,attendeeIds:selected})});const x=await r.json();if(!r.ok){setMsg(x.error||"Unable to book");return}location.href="/bootcamps/confirmed?booking_id="+encodeURIComponent(x.id)}catch(e){setMsg("Please try again.")}finally{setBusy("")}}
 return <main><section className="membership-page"><p className="eyebrow">WRAYFITNESS AT HALL FARM</p><h1>Weekly bootcamps coming soon.</h1><p className="membership-lead">We're planning weekly WrayFitness bootcamps at Hall Farm. The timetable isn't confirmed yet, so bookings aren't open. Once dates are announced, a place will cost £12.50 PAYG or one membership credit. Solo covers one named member, Duo up to two and Trio up to three attending together.</p>
 {member&&<article className="notice"><h3>Who's attending from your membership?</h3><p>Select the named members coming to the same bootcamp. Your group uses just one credit, however many of you attend.</p>{people.map(p=><label className="check" key={p.user_id}><input type="checkbox" checked={selected.includes(p.user_id!)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,p.user_id!]:prev.filter(x=>x!==p.user_id))}/>{p.full_name||p.email}{p.is_owner?" (owner)":""}</label>)}{people.length===0&&<p>Please complete your membership registration and any required health review first.</p>}</article>}
 {msg&&<p className="bookingmessage" role="alert">{msg}</p>}{loading?<p>Loading classes…</p>:classes.length===0?<article className="notice"><h3>New classes coming soon</h3><p>We're finalising the bootcamp timetable. Check back shortly for dates and booking options.</p></article>:<div className="cards">{classes.map(c=><article key={c.id}><p className="eyebrow">{c.remaining>0?c.remaining+" places left":"FULLY BOOKED"}</p><h3>{c.title}</h3><p><strong>{new Date(c.starts_at).toLocaleString("en-GB",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/London"})}</strong></p><p>{Math.round((new Date(c.ends_at).getTime()-new Date(c.starts_at).getTime())/60000)} minutes</p>{c.description&&<p>{c.description}</p>}<div className="actions"><a className="primary" href={c.remaining?"/bootcamps/payg?classId="+encodeURIComponent(c.id):undefined} aria-disabled={!c.remaining} style={!c.remaining?{pointerEvents:"none",opacity:.45}:undefined}>PAYG · £{(c.price_pence/100).toFixed(2)}</a>{member&&<button className="secondary" disabled={!c.remaining||selected.length<1||selected.length>c.remaining||busy===c.id} onClick={()=>useCredit(c)}>Use 1 member credit {selected.length>0?"("+selected.length+" attending)":""}</button>}</div></article>)}</div>}
 {!member&&<p className="formhint">Already a member? <a href="/login">Sign in</a> to use your credit.</p>}<p className="formhint">Each attendee must complete their required health registration before training. Need help? <a href="/contact">Get in touch.</a></p>
 </section></main>
}
