import {adminClient} from "../../lib/supabase-server";
export const dynamic="force-dynamic";
type Plan={code:string;name:string;price_pence:number;monthly_bookings:number;named_members:number;guest_passes:number};
export default async function MembershipPage(){
 const {data:plans,error:e}=await adminClient().from("membership_plans").select("code,name,price_pence,monthly_bookings,named_members,guest_passes").eq("active",true).order("price_pence");
 const{data:spots,error:spotError}=await adminClient().rpc("membership_places_remaining");const places=spotError?null:Number(spots);
 const loading=false,error=e?"Membership plans aren't available right now. Please try again shortly.":"";
 return <main><section className="membership-page"><p className="eyebrow">JOIN THE HALL FARM GYM</p><h1>Choose your membership.</h1><p className="membership-intro">Your own private space, without crowds, waiting around or other gym users watching you. Train at your own pace, build confidence or film your workouts. Choose whether to come alone, with a partner or as a group of three. A shower is available within your 50-minute session.</p>
 <article className="notice"><strong>Limited to 40 memberships in total.</strong><p>To make sure our members can still get the sessions they want, we are releasing just 35 memberships initially and keeping five in reserve. {places===null?"Please check current availability before joining.":places>0?`${places} of the initial 35 places currently available.`:"The first 35 membership places are currently full."}</p></article>{loading&&<p>Loading memberships…</p>}{error&&<p role="alert">{error}</p>}
 <div className="cards membership-cards">{(plans||[]).map(p=><article key={p.code}><h3>{p.name}</h3><div className="price">£{(p.price_pence/100).toFixed(p.price_pence%100?2:0)}<small>/month</small></div><p><strong>{p.monthly_bookings} private gym bookings each month</strong></p><p>{p.named_members===1?"The whole gym to yourself.":p.named_members===2?"You and your partner can train together during each booked session.":"All three named members can train together during each booked session."}</p><p>Each visit uses one booking, however many named members train together. Your membership renews automatically each month. Cancel any time; it ends when your current paid month finishes, with no cancellation fee.</p>{places===null?<a className="primary membership-cta" href={`/join?plan=${encodeURIComponent(p.code)}`}>Check availability</a>:places>0?<a className="primary membership-cta" href={`/join?plan=${encodeURIComponent(p.code)}`}>Choose {p.name} membership</a>:<a className="secondary membership-cta" href="/contact">Memberships currently full</a>}</article>)}</div>
 <p className="membership-note">Each booking reserves the whole gym for your group, including use of the shower during the booked 50 minutes. You can add one extra non-member to a session for £5. <a href="/terms-of-service">See our membership terms</a>.</p>
 <p className="membership-note">Rolling monthly membership: your selected plan is charged automatically each month until you cancel. Cancel in My Account whenever you like; you keep access until the end of the month you have already paid for. No minimum term or extra notice-period charge.</p><p className="membership-note">Not ready to join? <a href="/book">Book a PAYG session instead.</a></p></section></main>
}
