"use client";import{useEffect,useState}from"react";import{supabase}from"../../lib/supabase";
type S={starts_at:string;ends_at:string;is_available:boolean};
const key=(x:string)=>new Date(x).toLocaleDateString("en-CA",{timeZone:"Europe/London"});
const dayParts=(d:string)=>{const dt=new Date(d+"T12:00:00");return{dow:dt.toLocaleDateString("en-GB",{weekday:"short"}),date:dt.toLocaleDateString("en-GB",{day:"numeric"}),month:dt.toLocaleDateString("en-GB",{month:"short"}),full:dt.toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"})}};
export default function Book(){const[s,setS]=useState<S[]>([]),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[guest,setGuest]=useState(false),[party,setParty]=useState(1),[day,setDay]=useState("");
async function load(){const now=new Date(),f=now<new Date("2027-01-01T00:00:00Z")?new Date("2027-01-01T00:00:00Z"):now,t=new Date(f.getTime()+8*864e5);const{data}=await supabase().rpc("available_bookings",{p_from:f.toISOString(),p_to:t.toISOString()});setS(data||[]);setLoading(false)}useEffect(()=>{load()},[]);
async function memberBook(x:S){const sb=supabase();const{data:{user}}=await sb.auth.getUser();if(!user){location.href="/login";return}const{data:on}=await sb.rpc("onboarding_status");const status=on?.[0];if(!(status?.profile_complete&&status?.health_complete&&status?.legal_complete&&!status?.needs_review)){location.href="/onboarding?next=book";return}setBusy(x.starts_at);const{error}=await sb.rpc("book_member_slot",{p_starts_at:x.starts_at,p_party_size:party,p_bringing_guest:guest});setMsg(error?.message||"Booked — that session is yours.");setBusy("");await load()}
async function payg(x:S){const sb=supabase();const{data:{user}}=await sb.auth.getUser();if(!user){location.href="/login";return}const{data:on}=await sb.rpc("onboarding_status");const status=on?.[0];if(!(status?.profile_complete&&status?.health_complete&&status?.legal_complete&&!status?.needs_review)){location.href="/onboarding?next=book";return}setBusy(x.starts_at);const{data:{session}}=await sb.auth.getSession();const r=await fetch("/api/stripe/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({type:"payg",startsAt:x.starts_at,partySize:party})});const j=await r.json();if(j.url)location.href=j.url;else{setMsg(j.error||"Could not start payment.");setBusy("");await load()}}
const days=[...new Set(s.map(x=>key(x.starts_at)))],selected=day||days[0]||"",visible=s.filter(x=>key(x.starts_at)===selected),available=visible.filter(x=>x.is_available).length;
return <main><section className="booking"><p className="eyebrow">BOOK THE WHOLE GYM</p><h2>Choose your session</h2><p className="bookingintro">Choose a day and time below. Once you book, that 50-minute session is yours — nobody else can book the gym at the same time.</p><div className="bookingrule"><strong>Members: 7 days ahead</strong><span>PAYG: 3 days ahead</span></div>
<h3 className="bookingstep">1. Choose a day</h3>{loading&&<p className="emptybooking">Loading available sessions…</p>}{!loading&&days.length===0&&<div className="emptybooking"><strong>Bookings aren’t open yet.</strong><p>We open on 1 January 2027. Members can start booking from 25 December, and PAYG bookings open from 29 December.</p></div>}<div className="daystrip">{days.map(d=>{const p=dayParts(d),n=s.filter(x=>key(x.starts_at)===d&&x.is_available).length;return <button key={d} className={d===selected?"daycard selected":"daycard"} onClick={()=>setDay(d)}><span>{p.dow}</span><strong>{p.date}</strong><small>{p.month}</small><em>{n} free</em></button>})}</div>
<div className="bookingoptions"><label><span>People attending</span><select value={party} onChange={e=>setParty(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="guesttoggle"><input type="checkbox" checked={guest} onChange={e=>{const v=e.target.checked;setGuest(v);if(v&&party<2)setParty(2)}}/><span><strong>Bring a friend</strong><small>Members only · uses your free monthly guest pass</small></span></label></div>
{msg&&<p className="bookingmessage">{msg}</p>}<div className="timeshead"><div><h3 className="bookingstep">2. Choose a time</h3><p>{selected?dayParts(selected).full:"Choose a day above"}</p></div>{selected&&<strong>{available} available</strong>}</div><div className="timegrid">{visible.map(x=><article className={x.is_available?"timecard":"timecard unavailable"} key={x.starts_at}><div className="timestatus"><strong>{new Date(x.starts_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/London"})}</strong><span>{x.is_available?"Available":"Booked"}</span></div>{x.is_available&&<div className="timeactions"><button className="primary" disabled={busy===x.starts_at} onClick={()=>memberBook(x)}>Use member session</button><button className="secondary" disabled={busy===x.starts_at} onClick={()=>payg(x)}>Pay £12.50</button></div>}</article>)}</div></section></main>}