"use client";
import {useEffect,useState} from "react";
const questions:[string,string][]=[
 ["heart_condition","Has a doctor advised you to exercise only under medical supervision, or do you have a heart condition?"],
 ["chest_pain","Do you experience chest pain during exercise or at rest?"],
 ["dizziness","Do you experience dizziness, loss of balance or loss of consciousness?"],
 ["medical_reason","Is there any other medical reason not to exercise without professional advice?"]
];
export default function ClassPayg(){
 const[id,setId]=useState(""),[c,setC]=useState<any>(null),[f,setF]=useState({name:"",email:"",phone:"",emergencyName:"",emergencyPhone:""}),[answers,setAnswers]=useState<Record<string,boolean>>({}),[terms,setTerms]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{const x=new URLSearchParams(location.search).get("classId")||"";setId(x);fetch("/api/bootcamps").then(r=>r.json()).then(j=>setC((j.classes||[]).find((v:any)=>v.id===x)||null)).catch(()=>setMsg("Class unavailable"))},[]);
 async function pay(e:React.FormEvent){e.preventDefault();if(!id||questions.some(([k])=>typeof answers[k]!=="boolean")||!terms||!consent){setMsg("Complete every health question and consent.");return}setBusy(true);setMsg("");try{const r=await fetch("/api/bootcamps/payg",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,answers,classId:id,acceptTerms:terms,healthConsent:consent})});const j=await r.json();if(!r.ok||!j.url){setMsg(j.error||"Unable to start payment.");setBusy(false);return}location.href=j.url}catch(e){setMsg("Please try again.");setBusy(false)}}
 return <main><section className="policy payg-form"><p className="eyebrow">BOOTCAMP · PAY AS YOU GO</p><h2>Book your place.</h2>{c?<article className="notice"><h3>{c.title}</h3><p>{new Date(c.starts_at).toLocaleString("en-GB",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/London"})} · £{(c.price_pence/100).toFixed(2)} per person</p></article>:<p>Select a class from <a href="/bootcamps">the timetable</a>.</p>}
 <p>No account needed. Complete your details, short PAR-Q and payment to reserve one place.</p>
 <form onSubmit={pay}><h3>Your details</h3><div className="formgrid">{([["name","Full name","text"],["email","Email address","email"],["phone","Phone number","tel"],["emergencyName","Emergency contact name","text"],["emergencyPhone","Emergency contact phone","tel"]] as const).map(([key,label,type])=><input key={key} type={type} required aria-label={label} placeholder={label} value={f[key]} onChange={e=>setF(old=>({...old,[key]:e.target.value}))}/>)}</div><h3>Health questionnaire</h3>{questions.map(([key,q])=><label className="question" key={key}><span>{q}</span><select required aria-label={q} value={answers[key]===undefined?"":String(answers[key])} onChange={e=>setAnswers(old=>({...old,[key]:e.target.value==="true"}))}><option value="" disabled>Choose…</option><option value="false">No</option><option value="true">Yes</option></select></label>)}
 <label className="check"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to WrayFitness using these health answers to assess whether I can safely participate.</label><label className="check"><input required type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/>I agree to the <a href="/terms-of-service" target="_blank" rel="noopener noreferrer">booking and cancellation terms</a> and have read the <a href="/privacy-policy" target="_blank" rel="noopener noreferrer">privacy policy</a>.</label>
 {msg&&<p role="alert" className="bookingmessage">{msg}</p>}<button className="primary" type="submit" disabled={busy||!c||c.remaining<1}>{busy?"Opening Stripe…":"Pay £12.50 and book"}</button></form></section></main>
}
